version: '3.3'

services:
    prometheus:
        container_name: prometheus
        restart: unless-stopped
        ports:
            - '9090:9090'
        volumes:
            # persist data, see: https://github.com/prometheus/prometheus/pull/8747
            - prometheus:/prometheus
        image: prom/prometheus

volumes:
  prometheus: