version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'SUPERSECRETPASSWORD'
    volumes:
      - '/path/to/storage:/etc/pihole'
      - '/path/to/storage:/etc/dnsmasq.d'
    restart: unless-stopped