apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # base-64 encoded secret
  # /bin/bash echo -n 'something to encode in base64' | base64
  # see: https://en.wikipedia.org/wiki/Base64
  mongo-root: YWRtaW4=
  mongo-pass: YWRtaW5wYXNzd29yZA==
