version: '3.2'

services:
  app:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8585:80
    restart: unless-stopped
    volumes:
      - /path/to/storage:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOURSUPERSECRETPASSWORD
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    container_name: postgresdb
    volumes:
      - /path/to/storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOURSUPERSECRETPASSWORD
