version: '3.3'

services:
    dailynotes:
        container_name: dailynotes
        ports:
            - '5000:5000'
        volumes:
            - dailynotes:/app/config
        image: m0ngr31/dailynotes

volumes:
  dailynotes: