version: "3.3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Windoek
    volumes:
      - heimdall:/config
    ports:
      - 8081:80
      - 8444:443
    restart: unless-stopped

volumes:
  heimdall: