version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1001:1001 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - navi-data::/data
      - "/path/to/music:/music:ro"

volumes:
  navi-data: