version: '3.3'

services:
    grafana:
        container_name: grafana
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - grafana:/var/lib/grafana
        image: grafana/grafana-oss:latest

volumes:
  grafana: