---
version: "3"
services:
  updog:
    image: localbuild/updog
    container_name: updog
    user: 10001:10001
    volumes:
      - /updog/uploads:/uploads
    ports:
      - 9091:9090
    restart: unless-stopped
